name: Push CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Format
      run: dartfmt -w --fix .
    - name: Commit changes
      uses: EndBug/add-and-commit@v4.2.0
      with:
        author_name: Aditya Kishore
        author_email: AKushWarrior@gmail.com
        message: "Reformat using dartfmt"
        add: "*.dart"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
